### ISSUE TITLE
How to donate to support you?

### ISSUE THREAD

**Issue by xrdavies** [FastGitORG/Sponsors#3]
Thank you for your great jobs!
I would like to donate coins to support you even though it's very small.

**Comment by KevinZonda** [comment]
Hi there! Thanks for your support! You may find related information at <https://doc.fastgit.org/en-us/sponsor.html>.

**Comment by xrdavies** [comment]
> Hi there! Thanks for your support! You may find related information at https://doc.fastgit.org/en-us/sponsor.html.

Done! Thank you so much!

**Comment by KevinZonda** [comment]
Thanks for your help! 
453ab886c0d0f535abefd994cbccc5db614ac08a
