### ISSUE TITLE
请教该服务是如何搭建的？

### ISSUE THREAD

**Issue by ixmu** [FastGitORG/Sponsors#5]
请教该服务是如何搭建的？

**Comment by KevinZonda** [comment]
FastGit 的核心依赖于 NGINX，我们已经将最核心所需的 NGINX 配置开源至 <https://github.com/FastGitORG/nginx-conf>，具体搭建流程大概是

- 购买服务器
- 安装 Nginx
- 使用我们的配置进行修改并应用
- 测试并享受成功的喜悦
